# Generated by Django 3.2 on 2022-12-06 14:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=16, unique=True, verbose_name='Номер аккаунта')),
                ('account_type', models.IntegerField(default=1)),
            ],
            options={
                'db_table': 'accounts',
            },
        ),
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='ФИО')),
                ('citizenship', models.CharField(default='Кыргызстан', max_length=20, verbose_name='Гражданство')),
                ('birth_year', models.DateField(verbose_name='Год рождения')),
                ('work_place', models.CharField(blank=True, max_length=30, null=True, verbose_name='Место работы')),
                ('update_date', models.DateField(auto_now=True, verbose_name='Дата последнего обновления')),
            ],
            options={
                'db_table': 'customers',
            },
        ),
        migrations.CreateModel(
            name='Credit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sum', models.IntegerField(verbose_name='Сумма кредита')),
                ('date', models.DateField(auto_now_add=True, verbose_name='Дата получения кредита')),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='credits', to='credit.account')),
            ],
            options={
                'db_table': 'loans',
            },
        ),
        migrations.AddField(
            model_name='account',
            name='client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='accounts', to='credit.client'),
        ),
    ]
